import type { MetadataRoute } from "next";

// Web App Manifest — makes the site installable on Android (via Chrome's
// "Install app" prompt) and on iOS (via Share → "Add to Home Screen").
// Next.js App Router will serve this at /manifest.webmanifest.

export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "CS2 Major Pickems",
    short_name: "Pickems",
    description:
      "Predict CS2 Major outcomes, simulate the bracket, and track your score in real time.",
    start_url: "/bracket",
    scope: "/",
    display: "standalone",
    orientation: "portrait",
    background_color: "#0b0d12",
    theme_color: "#0b0d12",
    categories: ["sports", "entertainment", "games"],
    icons: [
      // The trophy emoji icons generated by app/icon.tsx + app/apple-icon.tsx
      // are auto-discovered. We also list them explicitly here at the sizes
      // Chrome wants for the install prompt; Next.js renders them from the
      // same handler when requested.
      { src: "/icon", sizes: "32x32", type: "image/png" },
      { src: "/apple-icon", sizes: "180x180", type: "image/png", purpose: "any" },
      { src: "/apple-icon", sizes: "180x180", type: "image/png", purpose: "maskable" },
    ],
  };
}
